social_media:
  facebook_share:
    text: 'Jaa Facebook-palvelussa'
  linkedin:
    text: 'Jaa Linkedin-palvelussa'
  twitter:
    text: 'Jaa Twitter-palvelussa'
  email:
    text: 'Lähetä sivu sähköpostitse'
