# File: drupal-helfi/azure-pipelines.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: aro-automaatio-demo-pipelines
    type: git
    # project/repository
    name: aro-automaatio-demo/aro-automaatio-demo-pipelines

extends:
  template: azure-pipelines-drupal.yml@aro-automaatio-demo-pipelines
