on: [push]
name: Tests and code
jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: druidfi/db:mysql5.7-drupal

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Build project
        run: |
          make new

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --verbose
