on: [push]
name: Tests and code
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      db:
        image: druidfi/db:mysql5.7-drupal

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Build project
        run: |
          composer install
          php -d sendmail_path=$(which true); drush --yes -v site-install --existing-config --db-url="$SIMPLETEST_DB"
          drush runserver $SIMPLETEST_BASE_URL > /dev/null 2>&1 &

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --verbose
